### ISSUE TITLE
T letter is missing in english keyboard

### ISSUE THREAD

**Issue by altafc22** [eebo0o/Unity-Arabic-English-Keyboard#1]
T letter is missing in english keyboard

**Comment by eebo0o** [comment]
Issue had been fixed and new release pushed.
"t" latter was only missed in the small letter alphabets due typo mistake it was switched with "q" letter there was 2 "q" letter in the keyboard.
Thank you for reporting that.

**Comment by altafc22** [comment]
Thanks for quick fix, really appreciate it.
